- hosts: localhost
  connection: local
  
  tasks:
    - name: Start
      liberty_server:
        state: started
        libertydir: "{{ libertydir }}"
        servername: "{{ servername }}"
      #become: yes
      #become_user: wasusr
      #become_method: sudo 
      register: rc

    - debug:
        msg: "{{ rc }}"
