- hosts: all
  #connection: local
  
  tasks:
    - name: Start
      ihs_ops:
        state: started
        ihsdir: "{{ ihsdir }}"
        servername: "{{ servername }}"
      become: yes
      become_user: ihsusr
      become_method: sudo 
      register: rc

    - debug:
        msg: "{{ rc }}"
