- hosts: localhost
  connection: local
  
  tasks:
    - name: Start
      liberty_server:
        state: started
        libertydir: "{{ libertydir }}"
        name: "{{ name }}"
      register: rc

    - debug:
        msg: "{{ rc }}"
