- hosts: localhost
  connection: local

  tasks:
    - name: Stop
      liberty_server:
        state: stopped
        libertydir: "{{ libertydir }}"
        name: "{{ name }}"
      register: rc

    - debug:
        msg: "{{ rc }}"
