- hosts: localhost
  connection: local

  tasks:
    - name: Stop
      liberty_server:
        state: stopped
        libertydir: "{{ libertydir }}"
        name: "{{ name }}"
      #become: yes
      #become_user: wasusr
      #become_method: sudo 
      register: rc

    - debug:
        msg: "{{ rc }}"
